# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://4freen.github.io/
baseurl: /home
title: Afreen Siraj
author: Afreen Siraj
description: Personal blog and resume
avatar: profile.png
email: afreen.siraj1@gmail.com
github: 4freen # username
twitter: AfreenSiraj
linkedin: AfreenS
# stackoverflow: username   #e.g: users/2735833/proton1h1
# Comment out if you don't want disqus
disqus: 4freen
comments: true
google_analytics: UA-55626988-1


# needed for travis-ci build
exclude: [vendor]
